### ISSUE TITLE
Some questions about the progress of the tsunami plug-in program

### ISSUE THREAD

**Issue by hh-hunter** [google/tsunami-security-scanner-plugins#281]
@maoning 
hi,I submitted a long time ago a zabbix fingerprinting plug-in and a VMware vulnerability detection has not made any progress, please tell me what is the problem? Or has this rewards program been terminated and the community is no longer doing any updates? I believe that many people who are concerned about this project have the same question, and we have been waiting for your reply.

#245 
#272

**Comment by maoning** [comment]
Hi @hh-hunter, we are also aware of the fact that the general review time is longer than what's needed to make Tsunami ecosystem healthy. We are currently looking for ways to scale up the review panel internally so that we can reduce the average response time. The good news is that we don't have plan on pausing Tsunami development anytime soon, though we will need your patience while we work towards a more rapid review process.

I've left comments on the 2 requests you linked.

**Comment by hh-hunter** [comment]
If you like, I can participate in the internal audit team (remote).
