### ISSUE TITLE
PRP: Request CVE-2020-2551

### ISSUE THREAD

**Issue by pussycat0x** [google/tsunami-security-scanner-plugins#33]
Vulnerability details:

Type: Oracle WebLogic Server product of Oracle Fusion Middleware
Score: 9.80 Critical
Vector: CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H
References:
    - https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-2551
    - https://github.com/hktalent/CVE-2020-2551

The vulnerability should be remotely exploitable without authentication and user interaction. Yes
The detector should provide a reliable false-positive free detection report. Yes
The vulnerability should have a relatively large impact radius. Yes, Oracle WebLogic Server product of Oracle Fusion Middleware
Please let me know if this is in scope as I've already made the development.

**Comment by magl0** [comment]
Hi @pussycat0x,

Thanks for your request! This vulnerability is in scope for the reward program. Please submit our [participation form](https://docs.google.com/forms/d/1SH8gyUnaGY3ezXY864oEuDZoOxrE5gJHYkcoiB_bu8I) and you can start working on the development.

Since you submitted multiple requests, let's work on one issue at a time to ensure the quality of the detector!

Thanks!

**Comment by tooryx** [comment]
Hi @pussycat0x,

Given how old these requests are, I will proactively close them. If you still wish to contribute to tsunami, please open issue one at a time.

Thank you,
~tooryx
