### ISSUE TITLE
PRP: Request CVE-2021-26084 Confluence Server Webwork Pre-Auth OGNL Injection

### ISSUE THREAD

**Issue by wdjcy** [google/tsunami-security-scanner-plugins#37]
Hello,

I would like to start the implementation for a plugin that detects CVE-2021-26084 Confluence Server Webwork Pre-Auth OGNL Injection

Vulnerability details:

Type: Confluence Server Webwork Pre-Auth OGNL Injection
Score: 9.8 CRITICAL
Vector: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H
References:

https://nvd.nist.gov/vuln/detail/CVE-2021-26084
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-26084
http://packetstormsecurity.com/files/164013/Confluence-Server-7.12.4-OGNL-Injection-Remote-Code-Execution.html | 
http://packetstormsecurity.com/files/164122/Atlassian-Confluence-WebWork-OGNL-Injection.html | Exploit  Third Party 
https://jira.atlassian.com/browse/CONFSERVER-67940

The vulnerability should be remotely exploitable without authentication and user interaction. Yes

The detector should provide a reliable false-positive free detection report. Yes

The detection capability should be easy to verify using both vulnerable and fixed Docker images. Yes, this can be done easily.

The vulnerability should have a relatively large impact radius. Yes, Confluence Server is widely used more than 10000+ Instance are exposed in shodan

Please let me know if this is in scope as I've already made the development .

**Comment by magl0** [comment]
Hi @wdjcy,

Thanks for your request! This vulnerability is in scope for the reward program. Please submit our [participation form](https://docs.google.com/forms/d/1SH8gyUnaGY3ezXY864oEuDZoOxrE5gJHYkcoiB_bu8I) and you can start working on the development.

Since you submitted multiple requests, let's work on one issue at a time to ensure the quality of the detector!

Thanks!

**Comment by magl0** [comment]
Duplicate of #174
